### ISSUE TITLE
Mandatory phone numbers in German and European Markets.

### ISSUE THREAD

**Issue by SanalKumarK** [klarna/kco_rest_java#16]
Hi,

We are using the kco-rest version 2.2.0, and we have a requirement to set phone number field mandatory in klarna check out order page for German and EU market. 
As part of the thread https://github.com/klarna/kco_rest_java/issues/12, Klarna agreed to provide a patch for the above requirement in version 2.2.0. 

Please let us know, once its available.

Thanks,
Sanal

**Comment by alexions** [comment]
https://github.com/klarna/kco_rest_java/pull/17

**Comment by alexions** [comment]
Please note that the v2.2.x branch is considering as deprecated.

**Comment by alexions** [comment]
The new 2.2.4 version has been successfully released.
The Maven Central repo requires some time (from 15 minutes to 8 hours) to show the released package.

You can read about the v2.2.4 changes in the CHANGELOG: https://github.com/klarna/kco_rest_java/blob/v2.2/CHANGELOG.md

Reopen the issue if you faced any issues with the latest changes.

Cheers!

**Comment by SanalKumarK** [comment]
Cool! I will work with the version 2.2.4 and let you know the result.

Cheers!

**Comment by SanalKumarK** [comment]
Hey @alexions,  
Is it possible to set **options.setPhoneMandatory(true);** for all countries? or do we need to set the value based on the required countries? 
In our scenario, we have to make it mandatory for all the countries. So should we send the value TRUE always?

**Comment by alexions** [comment]
Hi @SanalKumarK 

It depends on your needs. If you need this field to be true all the time, you need to set this to true all the time when sending a request to the API endpoint.

**Comment by SanalKumarK** [comment]
The above patch solved the problem.
Thanks @alexions ,
