### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by javaee5** [klarna/kco_rest_java#33]
Hi,

I have got two questions : 
1- Where can I find the Javascript library to be used in my web page because what I've seen only was Javascript documentation ?

2- Can I have a simple the order json structure

**Comment by alexions** [comment]
Hi @javaee5 

I'm not clearly sure how the Java SDK is connected to the Javascript library question, but I will try to address it

1) This part is always depends on which Klarna product do you use. If you're talking about Klarna Checkout you don't need to include any JS libraries manually, it will be added automatically.
There is an explanation how to interact with the lib: 
https://developers.klarna.com/documentation/klarna-checkout/javascript-api/

If you're talking about the Klarna Payment you can find the JS instructions here: https://developers.klarna.com/documentation/klarna-payments/integration-guide/present-klarna-widget/

This page has an instruction where to find the lib and how to connect:

```
<script src="https://x.klarnacdn.net/kp/lib/v1/api.js" async></script>
```

Also this Klarna Payment lib has a ref: https://x.klarnacdn.net/kp/lib/v1/index.html


2) This point is also depends on the product you are going to use. But all the examples and JSON representations can be found here: https://developers.klarna.com/api/

For example check the right column for the Klarna Checkout "create order" action: https://developers.klarna.com/api/#checkout-api-order


You can contact Klarna support team by following this link in case if you have questions about integration steps: https://www.klarna.com/merchant-support

Thank you.
