### ISSUE TITLE
OSGi support

### ISSUE THREAD

**Issue by anton-johansson** [klarna/kco_rest_java#4]
I prefer communicating with Klarna Checkout with raw HTTP libraries (CXF & Jackson in our case), but I happened to notice that this library isn't OSGi friendly, so even if we wanted to use this SDK, we could not.

Might be something to look over!

**Comment by alexions** [comment]
Thank you for the feedback. The v2.2.x branch is not going to be updated to change the transport.
Check for the v3.0.x. You can specify your own HTTP Transport and ObjectMapper.
